infra: improve dev experience with automated checks (#119)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -22,15 +22,40 @@ jobs:
       - name: ESLint
         run: npm run ci:lint
 
+      # Re-enable once parsing errors are fixed
+      # - name: Upload linter reports
+      #   uses: dorny/test-reporter@v1
+      #   if: success() || failure()
+      #   with:
+      #     name: ESLint
+      #     path: reports/eslint-junit.xml
+      #     reporter: jest-junit
+
       - name: Jest
         run: npm run ci:test
+
+      - name: Upload test reports
+        uses: dorny/test-reporter@v1
+        if: success() || failure()
+        with:
+          name: Jest
+          path: reports/jest-junit.xml
+          reporter: jest-junit
 
       - name: Storybook CI
         run: |
           chmod +x "./dev/ci-storybook.sh"
           ./dev/ci-storybook.sh
         shell: bash
-      
+
+      - name: Upload test reports (Storybook)
+        uses: dorny/test-reporter@v1
+        if: success() || failure()
+        with:
+          name: Storybook
+          path: reports/storybook-junit.xml
+          reporter: jest-junit
+
       - name: Upload coverage reports to Codecov
         uses: codecov/codecov-action@v3
         with:
